// <auto-generated />
namespace Aplikacija.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nova12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nova12));
        
        string IMigrationMetadata.Id
        {
            get { return "202001031334372_nova12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
